name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - source
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          CUSTOM_DOMAIN: wiki.tesuri.org
